"""add_course_close_date

Revision ID: 77cdb6236db4
Revises: ca2a1c73d218
Create Date: 2026-08-22 06:21:03.700986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cdb6236db4'
down_revision: Union[str, None] = 'ca2a1c73d218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapeos', sa.Column('course_close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapeos', 'course_close_date')
    # ### end Alembic commands ###
