"""Add eventos_bot table

Revision ID: ca2a1c73d218
Revises: 4880f2b9ab35
Create Date: 2026-08-14 14:38:38.675968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2a1c73d218'
down_revision: Union[str, None] = '4880f2b9ab35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_room_id', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_bot_commit_sha'), 'eventos_bot', ['commit_sha'], unique=True)
    op.create_index(op.f('ix_eventos_bot_id'), 'eventos_bot', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_bot_matrix_room_id'), 'eventos_bot', ['matrix_room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_bot_matrix_room_id'), table_name='eventos_bot')
    op.drop_index(op.f('ix_eventos_bot_id'), table_name='eventos_bot')
    op.drop_index(op.f('ix_eventos_bot_commit_sha'), table_name='eventos_bot')
    op.drop_table('eventos_bot')
    # ### end Alembic commands ###
