"""Add discrepancias and event fields

Revision ID: 1ff6eb9eab6b
Revises: 9f8355976da6
Create Date: 2026-08-14 13:06:14.640542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ff6eb9eab6b'
down_revision: Union[str, Sequence[str], None] = '9f8355976da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrepancias_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('moodle_user_id', sa.Integer(), nullable=True),
    sa.Column('moodle_course_id', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('tipo_discrepancia', sa.String(), nullable=False),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_discrepancias_auditoria_commit_sha'), 'discrepancias_auditoria', ['commit_sha'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_discrepancias_auditoria_timestamp'), 'discrepancias_auditoria', ['timestamp'], unique=False, schema='metrics')
    op.add_column('eventos_sync', sa.Column('moodle_user_id', sa.Integer(), nullable=True), schema='metrics')
    op.add_column('eventos_sync', sa.Column('moodle_course_id', sa.Integer(), nullable=True), schema='metrics')
    op.add_column('eventos_sync', sa.Column('commit_sha', sa.String(), nullable=True), schema='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos_sync', 'commit_sha', schema='metrics')
    op.drop_column('eventos_sync', 'moodle_course_id', schema='metrics')
    op.drop_column('eventos_sync', 'moodle_user_id', schema='metrics')
    op.drop_index(op.f('ix_metrics_discrepancias_auditoria_timestamp'), table_name='discrepancias_auditoria', schema='metrics')
    op.drop_index(op.f('ix_metrics_discrepancias_auditoria_commit_sha'), table_name='discrepancias_auditoria', schema='metrics')
    op.drop_table('discrepancias_auditoria', schema='metrics')
    # ### end Alembic commands ###
