"""baseline

Revision ID: 9975d20fcbec
Revises: 
Create Date: 2026-08-13 10:16:47.384145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9975d20fcbec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos_sync',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_eventos_sync_timestamp'), 'eventos_sync', ['timestamp'], unique=False, schema='metrics')
    op.create_table('interacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('moodle_user_id', sa.Integer(), nullable=False),
    sa.Column('moodle_course_id', sa.Integer(), nullable=False),
    sa.Column('tipo_interaccion', sa.String(), nullable=False),
    sa.Column('referencia_evento', sa.String(), nullable=True),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_interacciones_moodle_course_id'), 'interacciones', ['moodle_course_id'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_interacciones_moodle_user_id'), 'interacciones', ['moodle_user_id'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_interacciones_timestamp'), 'interacciones', ['timestamp'], unique=False, schema='metrics')
    op.create_table('conceptos_detectados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaccion_id', sa.UUID(), nullable=False),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['interaccion_id'], ['metrics.interacciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_conceptos_detectados_interaccion_id'), 'conceptos_detectados', ['interaccion_id'], unique=False, schema='metrics')
    op.create_table('reversiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaccion_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interaccion_id'], ['metrics.interacciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_reversiones_interaccion_id'), 'reversiones', ['interaccion_id'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_reversiones_timestamp'), 'reversiones', ['timestamp'], unique=False, schema='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_reversiones_timestamp'), table_name='reversiones', schema='metrics')
    op.drop_index(op.f('ix_metrics_reversiones_interaccion_id'), table_name='reversiones', schema='metrics')
    op.drop_table('reversiones', schema='metrics')
    op.drop_index(op.f('ix_metrics_conceptos_detectados_interaccion_id'), table_name='conceptos_detectados', schema='metrics')
    op.drop_table('conceptos_detectados', schema='metrics')
    op.drop_index(op.f('ix_metrics_interacciones_timestamp'), table_name='interacciones', schema='metrics')
    op.drop_index(op.f('ix_metrics_interacciones_moodle_user_id'), table_name='interacciones', schema='metrics')
    op.drop_index(op.f('ix_metrics_interacciones_moodle_course_id'), table_name='interacciones', schema='metrics')
    op.drop_table('interacciones', schema='metrics')
    op.drop_index(op.f('ix_metrics_eventos_sync_timestamp'), table_name='eventos_sync', schema='metrics')
    op.drop_table('eventos_sync', schema='metrics')
    # ### end Alembic commands ###
