"""Add refresh_tokens and uq_interaccion_referencia_evento

Revision ID: ba95be90ae97
Revises: ff33af7a2c13
Create Date: 2026-08-15 13:30:49.910184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba95be90ae97'
down_revision: Union[str, Sequence[str], None] = 'ff33af7a2c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moodle_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_refresh_tokens_moodle_user_id'), 'refresh_tokens', ['moodle_user_id'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='metrics')
    
    op.create_unique_constraint('uq_interaccion_referencia_evento', 'interacciones', ['referencia_evento'], schema='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interaccion_referencia_evento', 'interacciones', schema='metrics', type_='unique')
    
    op.drop_index(op.f('ix_metrics_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='metrics')
    op.drop_index(op.f('ix_metrics_refresh_tokens_moodle_user_id'), table_name='refresh_tokens', schema='metrics')
    op.drop_table('refresh_tokens', schema='metrics')
    # ### end Alembic commands ###
