"""Add PII models

Revision ID: bf999a9c4337
Revises: 6d291a14e74e
Create Date: 2026-09-09 20:06:09.352847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf999a9c4337'
down_revision: Union[str, Sequence[str], None] = '6d291a14e74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('moodle_username', sa.String(), nullable=False),
    sa.Column('token_requested', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_pii_access_log_moodle_username'), 'pii_access_log', ['moodle_username'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_pii_access_log_timestamp'), 'pii_access_log', ['timestamp'], unique=False, schema='metrics')
    op.create_table('pii_vault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_matrix_id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('raw_value_encrypted', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='metrics'
    )
    op.create_index(op.f('ix_metrics_pii_vault_expires_at'), 'pii_vault', ['expires_at'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_pii_vault_interaction_id'), 'pii_vault', ['interaction_id'], unique=False, schema='metrics')
    op.create_index(op.f('ix_metrics_pii_vault_student_matrix_id'), 'pii_vault', ['student_matrix_id'], unique=False, schema='metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_pii_vault_student_matrix_id'), table_name='pii_vault', schema='metrics')
    op.drop_index(op.f('ix_metrics_pii_vault_interaction_id'), table_name='pii_vault', schema='metrics')
    op.drop_index(op.f('ix_metrics_pii_vault_expires_at'), table_name='pii_vault', schema='metrics')
    op.drop_table('pii_vault', schema='metrics')
    op.drop_index(op.f('ix_metrics_pii_access_log_timestamp'), table_name='pii_access_log', schema='metrics')
    op.drop_index(op.f('ix_metrics_pii_access_log_moodle_username'), table_name='pii_access_log', schema='metrics')
    op.drop_table('pii_access_log', schema='metrics')
    # ### end Alembic commands ###
